#! /bin/sh

read -r -d '' helptext <<EOF
usage: ff [OPTIONS]
  ff: wrap file finder with global/rg/fd/find
  generate .files.gz to cache the result from rg/fd/find
  gtags result is preferable than .files.gz
OPTIONS:
  -h: Print this usage
  -f: force re-generate index
EOF

if [ "$1" == "-h" ]; then
    echo "$helptext"
    exit 0
elif [ "$1" == "-f" ]; then
    shift
    regen=1
fi

folder="."
if [ "$#" -gt "0" ]; then
    folder=${1%/}
fi

# prefer gtags results
if global -Pol -S ${folder} 2>/dev/null; then
    exit 0
fi

if [ "${regen}" != "" ] || [ ! -e "${folder}/.files.gz" ]; then
    rm -rf ${folder}/.files ${folder}/.files.gz
    ( rg --no-messages --files --no-ignore ${folder} ||
        fd -t f -HIL . ${folder} ||
        find ${folder} -path "*/\.*" -prune -o -type f -print -o -type l -print ) 2>/dev/null |
        sed 's#^\.\/##' > ${folder}/.files
    pigz --best -fq ${folder}/.files
fi

pigz -dkcfq ${folder}/.files.gz
